"""Centralized conversation state IDs for all handlers."""

__all__ = [
    "STEP_START_LANGUAGE",
    "STEP_START_FUEL",
    "STEP_SEARCH_MODE",
    "STEP_SEARCH_LOCATION",
    "STEP_SEARCH_ROUTE_ORIGIN",
    "STEP_SEARCH_ROUTE_DESTINATION",
    "STEP_PROFILE_MENU",
    "STEP_PROFILE_LANGUAGE",
    "STEP_PROFILE_FUEL",
]

(
    # /start flow
    STEP_START_LANGUAGE,
    STEP_START_FUEL,
    # /search flow
    STEP_SEARCH_MODE,
    STEP_SEARCH_LOCATION,
    STEP_SEARCH_ROUTE_ORIGIN,
    STEP_SEARCH_ROUTE_DESTINATION,
    # /profile flow
    STEP_PROFILE_MENU,
    STEP_PROFILE_LANGUAGE,
    STEP_PROFILE_FUEL,
) = range(9)
